### ISSUE TITLE
Transfering file via imageserver

### ISSUE THREAD

**Issue by tribeiro** [astroufsc/chimera#94] opened 2015-07-25 08:54 UTC
When opening the file for writing here:

https://github.com/astroufsc/chimera/blob/c3b9daebb4115487bb0af7ab1bec716d3f8b46e2/src/chimera/controllers/imageserver/imageserverhttp.py#L36

The file is opened on "read" only. On Windows it causes problems during the transference. Replacing this by

    f = open(filename,"rb") # Read as Binary

solves the issue.

**Comment by wschoenell** [comment] 2015-07-26 20:12
@tribeiro,

Can you give more information on this? For me seems to be working. Can you repeat the test with the `chimera.config` below? Maybe the problem is related to the camera driver and not to the Image Server.

I have tried on LNA with this test:
1) Configure chimera on Windows 7 with this `chimera.config`:

	chimera:
	  host: 10.0.8.11
	  port: 7666
  
	site:
	 name: OPD
	 latitude: "-22:32:04"
	 longitude: "-45:34:57"
	 altitude: 1864

	telescope:
	   name: fake
	   type: FakeTelescope
	   min_altitude: 15
   
	camera:
	   name: fake
	   type: FakeCamera
	   use_dss: True

	controller:
	  - type: ImageServer
		name: imageserver
		httpd: True
		autoload: False

2) Took on Windows an exposure with `chimera-cam`.

3) Went to http://ip.addr:7669/ from another computer and downloaded the image from the Image Server without problems.

	26-07-2015 15:01:52.709 [localhost:7666] INFO chimera.controllers.imageserver.imageserver imageserverhttp.py:22 MACBOOKPRO-8D29 - - [26/Jul/2015 15:01:52] "GET /image/c0a800f508a47ac0af6a7362ff01325d HTTP/1.1" 200 -

**Comment by tribeiro** [comment] 2015-07-27 04:29
Just to let everyone know that @wschoenell and I went over this and where able to demonstrate the problem and its solution. I'll post the fixing PR.

**Comment by wschoenell** [comment] 2015-07-27 09:10
Fixed on #94.

**Closed by wschoenell** 2015-07-27 09:10 UTC
Labels: bug
